name: "Build docker image"
on:
  push:
    branches:
      - "master"
      - "development"
jobs:
  build-push-docker:
    name: "Build image and push docker hub registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add app.env
        env:
          APP_ENV: ${{ secrets.APP }}
        run: echo "$APP" > app.env
      - name: build image
        run: docker build -t zipzap11/workuo:latest .
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOKERHUB_PASSWORD }}
      - name: push image to dockerhub
        run: docker push zipzap11/workuo:latest
