name: Running Unit Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'development'

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.4
      - name: running unit test
        run: go test ./... -cover
